POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "mike@email.com",
  "password": "P@ssw0rd"
}

GET http://localhost:3000/auth/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWlrZUBlbWFpbC5jb20iLCJpYXQiOjE3MzAxODE2MTIsImV4cCI6MTczMDE4MjUxMiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTczIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.TJo-jxinHyll3DBvCH1iagT4RgrmDi8SsPMAImJvqeQ