POST http://localhost:3000/auth/login
Content-Type: application/json
{ "email": "mike@email.com", "password": "P@ssw0rd" }

POST http://localhost:3000/auth/refresh
Cookie: refreshToken=


POST http://localhost:3000/auth/logout
Cookie: refreshToken=

# P@ssw0rd